# .readthedocs.yaml
version: 2

# Define environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - numba

sphinx:
  configuration: docs/source/conf.py

# Optional
formats:
  - htmlzip
  - pdf
