# .github/workflows/publish-to-pypi.yml

name: Publicar Paquete de Python en PyPI

on:
  # Esto activa el workflow cada vez que publicas una "Release" en GitHub
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload a release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      # 1. Download code from repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. Install dependencies and build package
      - name: Install dependencies and build package
        run: python -m pip install build && python -m build

      # 4. Publish package to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
